### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cyberboysumanjay/JioSaavnAPI#32] opened 2021-02-16 13:59 UTC
https://gist.github.com/ParveenBhadooOfficial/521b15207420e5202fd82db47b768850
https://gist.github.com/ParveenBhadooOfficial/ea5a60c4435320c5b12cc00632a1c64c

happening randomly. why?

**Comment by cyberboysumanjay** [comment] 2021-02-23 07:11
Strange issue. Seems it is happening due to null query.
A condition to check null value just before invoking search should fix this. 
Will include this along with other set of changes which are coming soon 😄

**Comment by Chetan-Goyal** [comment] 2021-02-25 19:33
Can I work on this issue with all of the possible values which API may receive?

**Comment by AvTe** [comment] 2021-03-26 04:40
> 
> 
> https://gist.github.com/ParveenBhadooOfficial/521b15207420e5202fd82db47b768850
> https://gist.github.com/ParveenBhadooOfficial/ea5a60c4435320c5b12cc00632a1c64c
> 
> happening randomly. why?



If a function does not return anything, e.g.:

```
def test():
    pass
```

it has an implicit return value of None.

Thus, as your pick* methods do not return anything, e.g.:

```
def pickEasy():
    word = random.choice(easyWords)
    word = str(word)
    for i in range(1, len(word) + 1):
        wordCount.append("_")
```

the lines that call them, e.g.:

`word = pickEasy()`

set word to None, so wordInput in getInput is None. This means that:

if guess in wordInput:

is the equivalent of:

if guess in None:

and None is an instance of NoneType which does not provide iterator/iteration functionality, so you get that type error.

The fix is to add the return type:

```
def pickEasy():
    word = random.choice(easyWords)
    word = str(word)
    for i in range(1, len(word) + 1):
        wordCount.append("_")
    return word
```

**Comment by Chetan-Goyal** [comment] 2021-03-29 18:51
@ParveenBhadooOfficial I think this issue is resolved after my last pull request. If it still exists, please provide the steps to reproduce it. I will be happy to fix it.

**Comment by cyberboysumanjay** [comment] 2021-03-30 04:31
Great!
Closing this for now.
Feel free to re-open this so that we can look into it further, if problem persists.

**Closed by cyberboysumanjay** 2021-03-30 04:31 UTC
Labels: bug
